defaults:
  pulse:
    credentials:
      username: !env PULSE_USERNAME
      password: !env PULSE_PASSWORD
      hostname: pulse.mozilla.org
      vhost: '/'
    prefetch:   20
    queueName:  'taskcluster-task-analysis'
  postgresql: !env DATABASE_URL
  server:
    publicUrl: !env APPLICATION_URL
    port: !env:number PORT
    forceSSL: false
    trustProxy: false
trustProxy: false
production:
  monitor:
    component: 'task-analysis'
  server:
    publicUrl: !env APPLICATION_URL
    port: !env:number PORT
    forceSSL: true
    env: 'production'
    trustProxy: true
staging:
  pulse:
    queueName: taskcluster-task-analysis
  monitor:
    component: 'task-analysis-staging'
test:
  server:
    publicUrl: 'http://localhost:60415'
    port: 60415
    env: 'development'
    trustProxy: false
    forceSSL: false
  postgresql:
    host: localhost
    port: 5555
    user: postgres
    password: seekrit
    database: postgres
    max: 10
    idleTimeoutMillis: 1000
  monitor:
    component: 'task-analysis-test'
